name: delivery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.2.4
  google_sign_in: ^6.3.0
  http: ^1.4.0
  awesome_dialog: ^3.2.1
  curved_navigation_bar: ^1.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
    - assets/icons/
    - assets/menus/
    - assets/avatars/